# Generated by Django 3.0.5 on 2020-05-01 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice_meccanografico', models.CharField(max_length=14)),
                ('nome', models.CharField(max_length=40)),
                ('indirizzo', models.CharField(max_length=80)),
                ('descrizione', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(max_length=20)),
                ('cartella', models.CharField(max_length=20)),
                ('posizione', models.IntegerField()),
                ('visibile', models.BooleanField(default=True)),
                ('url_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('url_calendar', models.CharField(max_length=20)),
                ('url_feedback', models.CharField(max_length=20)),
                ('scuola_appartenenza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.School')),
            ],
        ),
    ]
