# Generated by Django 3.0.5 on 2020-05-01 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_classe_scuola'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classe',
            options={'verbose_name': 'Classe', 'verbose_name_plural': 'Classi'},
        ),
        migrations.AlterModelOptions(
            name='scuola',
            options={'verbose_name': 'School', 'verbose_name_plural': 'Scuole'},
        ),
    ]
