# Generated by Django 3.0.5 on 2020-05-03 16:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20200501_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contenuto',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
